<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-21T17:12:57+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.full_page_lifetime_value
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.2',
    'version_db_installed' => '20180122213656',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1521648574,
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
