<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-21T16:09:57+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.3.2',
    'version_db_installed' => '20180122213656',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1521648574,
    ],
];
