<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-03-21T16:08:10+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Tease + Company',
        ],
    ],
];
